CREATE TABLE [dbo].[JRankByScopus] (
    [Sourcerecord_id]                                                             FLOAT (53)     NOT NULL,
    [Journal]                                                                     NVARCHAR (MAX) NOT NULL,
    [Print_ISSN]                                                                  NVARCHAR (50)  NULL,
    [E_ISSN]                                                                      NVARCHAR (50)  NULL,
    [LangCode]                                                                    NVARCHAR (50)  NULL,
    [CiteScore16]                                                                 NVARCHAR (50)  NULL,
    [CiteScore17]                                                                 NVARCHAR (50)  NULL,
    [CiteScore18]                                                                 NVARCHAR (50)  NULL,
    [Open_Access_status_i_e_registered_in_DOAJ_and_or_ROAD_Status_September_2019] NVARCHAR (MAX) NULL,
    [Articles_in_Press_included]                                                  NVARCHAR (MAX) NULL,
    [Source_Type]                                                                 NVARCHAR (MAX) NOT NULL,
    [Title_history_indication]                                                    NVARCHAR (MAX) NULL,
    [Related_title_to_title_history_indication]                                   NVARCHAR (MAX) NULL,
    [Other_related_title_1]                                                       NVARCHAR (MAX) NULL,
    [Other_related_title_2]                                                       NVARCHAR (MAX) NULL,
    [Other_related_title_3]                                                       NVARCHAR (MAX) NULL,
    [Publisher_s_Name]                                                            NVARCHAR (MAX) NULL,
    [Publisher_imprints_grouped_to_main_Publisher]                                NVARCHAR (MAX) NULL,
    [Publisher_s_Country_Territory]                                               NVARCHAR (MAX) NOT NULL,
    [All_Science_Journal_Classification_Codes_ASJC]                               NVARCHAR (MAX) NOT NULL,
    [Top_level_Life_Sciences]                                                     NVARCHAR (MAX) NULL,
    [Top_level_Social_Sciences]                                                   NVARCHAR (MAX) NULL,
    [Top_level_Physical_Sciences]                                                 NVARCHAR (MAX) NULL,
    [Top_level_Health_Sciences]                                                   NVARCHAR (MAX) NOT NULL,
    [_1000_General]                                                               NVARCHAR (MAX) NULL,
    [_1100_Agricultural_and_Biological_Sciences]                                  NVARCHAR (MAX) NULL,
    [_1200_Arts_and_Humanities]                                                   NVARCHAR (MAX) NULL,
    [_1300_Biochemistry_Genetics_and_Molecular_Biology]                           NVARCHAR (MAX) NULL,
    [_1400_Business_Management_and_Accounting]                                    NVARCHAR (MAX) NULL,
    [_1500_Chemical_Engineering]                                                  NVARCHAR (MAX) NULL,
    [_1600_Chemistry]                                                             NVARCHAR (MAX) NULL,
    [_1700_Computer_Science]                                                      NVARCHAR (MAX) NULL,
    [_1800_Decision_Sciences]                                                     NVARCHAR (MAX) NULL,
    [_1900_Earth_and_Planetary_Sciences]                                          NVARCHAR (MAX) NULL,
    [_2000_Economics_Econometrics_and_Finance]                                    NVARCHAR (MAX) NULL,
    [_2100_Energy]                                                                NVARCHAR (MAX) NULL,
    [_2200_Engineering]                                                           NVARCHAR (MAX) NULL,
    [_2300_Environmental_Science]                                                 NVARCHAR (MAX) NULL,
    [_2400_Immunology_and_Microbiology]                                           NVARCHAR (MAX) NULL,
    [_2500_Materials_Science]                                                     NVARCHAR (MAX) NULL,
    [_2600_Mathematics]                                                           NVARCHAR (MAX) NULL,
    [_2700_Medicine]                                                              NVARCHAR (MAX) NOT NULL,
    [_2800_Neuroscience]                                                          NVARCHAR (MAX) NULL,
    [_2900_Nursing]                                                               NVARCHAR (MAX) NULL,
    [_3000_Pharmacology_Toxicology_and_Pharmaceutics]                             NVARCHAR (MAX) NULL,
    [_3100_Physics_and_Astronomy]                                                 NVARCHAR (MAX) NULL,
    [_3200_Psychology]                                                            NVARCHAR (MAX) NULL,
    [_3300_Social_Sciences]                                                       NVARCHAR (MAX) NULL,
    [_3400_Veterinary]                                                            NVARCHAR (MAX) NULL,
    [_3500_Dentistry]                                                             NVARCHAR (MAX) NULL,
    [_3600_Health_Professions]                                                    NVARCHAR (MAX) NULL
);

