CREATE TABLE [dbo].[KeywordTFIDF] (
    [paper_id]                               VARCHAR (40) NOT NULL,
    [title_avail]                            VARCHAR (1)  NOT NULL,
    [abstract_avail]                         VARCHAR (1)  NOT NULL,
    [body_text_avail]                        VARCHAR (1)  NOT NULL,
    [count_total_words]                      BIGINT       NULL,
    [tfidf_transmission]                     FLOAT (53)   NULL,
    [tfidf_incubation]                       FLOAT (53)   NULL,
    [tfidf_environmental_stability]          FLOAT (53)   NULL,
    [tfidf_risk]                             FLOAT (53)   NULL,
    [tfidf_virus]                            FLOAT (53)   NULL,
    [tfidf_genetics]                         FLOAT (53)   NULL,
    [tfidf_origin]                           FLOAT (53)   NULL,
    [tfidf_evolution]                        FLOAT (53)   NULL,
    [tfidf_vaccines]                         FLOAT (53)   NULL,
    [tfidf_therapeutics]                     FLOAT (53)   NULL,
    [tfidf_non_pharmaceutical_interventions] FLOAT (53)   NULL,
    [tfidf_published]                        FLOAT (53)   NULL,
    [tfidf_medical_care]                     FLOAT (53)   NULL,
    [tfidf_ethical]                          FLOAT (53)   NULL,
    [tfidf_social_science]                   FLOAT (53)   NULL,
    [tfidf_diagnostics]                      FLOAT (53)   NULL,
    [tfidf_surveillance]                     FLOAT (53)   NULL,
    [tfidf_information_sharing]              FLOAT (53)   NULL,
    [tfidf_inter_sectoral_collaboration]     FLOAT (53)   NULL,
    [tfidf_covid19]                          FLOAT (53)   NULL,
    [tfidf_sarscov2]                         FLOAT (53)   NULL
);

