CREATE TABLE [dbo].[KeywordCounts] (
    [paper_id]                               VARCHAR (40) NOT NULL,
    [title_avail]                            VARCHAR (1)  NOT NULL,
    [abstract_avail]                         VARCHAR (1)  NOT NULL,
    [body_text_avail]                        VARCHAR (1)  NOT NULL,
    [count_transmission]                     INT          NOT NULL,
    [count_incubation]                       INT          NOT NULL,
    [count_environmental_stability]          INT          NOT NULL,
    [count_risk]                             INT          NOT NULL,
    [count_virus]                            INT          NOT NULL,
    [count_genetics]                         INT          NOT NULL,
    [count_origin]                           INT          NOT NULL,
    [count_evolution]                        INT          NOT NULL,
    [count_vaccines]                         INT          NOT NULL,
    [count_therapeutics]                     INT          NOT NULL,
    [count_non_pharmaceutical_interventions] INT          NOT NULL,
    [count_published]                        INT          NOT NULL,
    [count_medical_care]                     INT          NOT NULL,
    [count_ethical]                          INT          NOT NULL,
    [count_social_science]                   INT          NOT NULL,
    [count_diagnostics]                      INT          NOT NULL,
    [count_surveillance]                     INT          NOT NULL,
    [count_information_sharing]              INT          NOT NULL,
    [count_inter_sectoral_collaboration]     INT          NOT NULL,
    [count_covid19]                          INT          NOT NULL,
    [count_sarscov2]                         INT          NOT NULL,
    [count_total_keywords]                   INT          NULL
);

